# Generated by Django 4.0.3 on 2022-04-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
